### PR TITLE
Expose whether PPS is supported with getExistPPS

### PR DESCRIPTION
**Pull request by Patronics**

### CODE REVIEW

**Comment by centydev** [comment]
Hi Patrick,

I will let you double-check the current multiplier first. Last time I check 50mA works on PocketPD.

**Comment by Patronics** [comment]
Sorry, I didn't mean to push the getMaxCurrentForVoltage changes to your repo yet, GitHub automatically added them to my pull request for getExistPPS since I pushed them to the same branch. I'll do some testing, and report back with my results (and/or push changes to fix it as needed)

**Comment by Patronics** [comment]
Okay, I've tested and fixed GetMaxCurrentForVoltage (along with a fix for your getMaxCurrent function when PPS is unavailable), it seems to work in all my testing so far. If possible, it'd be great if you could test it a bit more with your hardware, and merge it in once you've confirmed it behaves as expected for you.

**Comment by centydev** [comment]
Hi Patrick, I will check the feature in the next three days. Thank you!

Function to test:

- GetMaxCurrentForVoltage - Test at all fixed PDOs and some random PPS voltage selection
- getMaxCurrent - Test for PDOs and PPS profile

**Review by centydev — APPROVED** [review]

**Pull request merged**
